import React, { useState, useEffect } from 'react';
import { Template, TemplateImage } from '../types';
import { 
  ArrowLeft, Check, Download, Heart, Share2, 
  Maximize2, BookmarkPlus, 
  ChevronLeft, ChevronRight, FolderPlus, 
  ZoomIn, ZoomOut, RotateCcw, Eye, Star, Send,
  MoreVertical, Flag, Loader2, ChevronDown, ChevronUp, Search, X,
  PenTool, Trash2, Plus, Layers, MonitorSmartphone, Palette
} from 'lucide-react';
// @ts-ignore
import JSZip from 'jszip';
import { saveToStorage } from '../services/storage';
import { generateTemplateImage } from '../services/gemini';

interface TemplateDetailsProps {
  template: Template;
  allTemplates?: Template[];
  onBack: () => void;
  isLiked?: boolean;
  onLike: (id: string) => void;
  onDownload?: (id: string) => void;
  onNavigateToDetails?: (template: Template) => void;
  onUpdateTemplate?: (updatedTemplate: Template) => void;
}

interface Comment {
  id: string;
  user: {
    name: string;
    avatar: string;
  };
  rating: number;
  date: string;
  content: string;
}

const REPORT_REASONS = [
  { id: 'inappropriate', label: 'Inappropriate Content' },
  { id: 'copyright', label: 'Copyright Violation' },
  { id: 'misleading', label: 'Misleading Information' },
  { id: 'broken', label: 'Broken / Not Working' },
  { id: 'spam', label: 'Spam' },
  { id: 'other', label: 'Other' }
];

const generatePRD = (template: Template, images: TemplateImage[]): string => {
  const date = new Date().toLocaleDateString();
  
  return `# Product Requirements Document (PRD)
# ${template.title}

**Version:** ${template.version}
**Date:** ${date}
**Category:** ${template.category}
**Author:** ${template.author.name}

---

## 1. Executive Summary
${template.description}

## 2. Project Scope & Specifications

### 2.1 Target Audience
Users looking for a ${template.category} solution with a focus on ${template.tags.slice(0, 3).join(', ')}.

### 2.2 Technical Requirements
- **Compatible Software:** ${Object.entries(template.compatibility).filter(([_, v]) => v).map(([k]) => k).join(', ')}
- **Responsive:** Yes
- **License:** ${template.pricing}

## 3. Key Features & Functional Requirements

The following features have been defined for the MVP (Minimum Viable Product):

${template.features.map((feature, index) => `### 3.${index + 1} ${feature}
- **Description:** Implement ${feature} interface and logic.
- **Priority:** High
- **Acceptance Criteria:** User must be able to interact with ${feature} without layout breaks.
`).join('\n')}

## 4. UI/UX Assets List

The package includes the following visual assets (located in /assets folder):

${images.map((img, i) => `- **${img.caption}**: ${img.type} preview`).join('\n')}

---
*Generated by DG Studio AI Template Manager*
`;
};

const TemplateDetails: React.FC<TemplateDetailsProps> = ({ 
  template, 
  allTemplates = [], 
  onBack, 
  isLiked = false, 
  onLike,
  onDownload,
  onNavigateToDetails,
  onUpdateTemplate
}) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'features' | 'reviews' | 'related'>('overview');
  const [showShareMenu, setShowShareMenu] = useState(false);
  const [isCopied, setIsCopied] = useState(false);
  const [showUseConfirmation, setShowUseConfirmation] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [isDescriptionExpanded, setIsDescriptionExpanded] = useState(false);
  
  // Collections State
  const [userCollections, setUserCollections] = useState<Record<string, string[]>>({});
  const [showCollectionModal, setShowCollectionModal] = useState(false);
  const [newCollectionName, setNewCollectionName] = useState('');
  
  // Report State
  const [showReportModal, setShowReportModal] = useState(false);
  const [selectedReason, setSelectedReason] = useState(REPORT_REASONS[0].id);
  const [reportDescription, setReportDescription] = useState('');
  const [showMenu, setShowMenu] = useState(false);

  // Reviews State
  const [comments, setComments] = useState<Comment[]>([
    {
      id: '1',
      user: { name: 'Alex M.', avatar: 'https://ui-avatars.com/api/?name=Alex+M&background=0ea5e9&color=fff' },
      rating: 5,
      date: '2 days ago',
      content: 'Absolutely love the attention to detail in this kit. The auto-layout is perfect.'
    },
    {
      id: '2',
      user: { name: 'Sarah L.', avatar: 'https://ui-avatars.com/api/?name=Sarah+L&background=8b5cf6&color=fff' },
      rating: 4,
      date: '1 week ago',
      content: 'Great starting point for my project. Would love to see more dashboard widgets in the next update.'
    }
  ]);
  const [newComment, setNewComment] = useState('');
  const [newRating, setNewRating] = useState(5);

  // Images
  const hasImages = Array.isArray(template.images) && template.images.length > 0;
  const fallbackImages = [{
    url: `https://image.pollinations.ai/prompt/${encodeURIComponent(template.title + ' mobile app ui design')}?width=1024&height=768&nologo=true`,
    caption: 'Visão Geral',
    type: 'mockup' as const
  }];
  const images = hasImages ? template.images : fallbackImages;
  const [activeImageIndex, setActiveImageIndex] = useState(0);
  const [isZoomModalOpen, setIsZoomModalOpen] = useState(false);
  const [zoomLevel, setZoomLevel] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });
  const [toast, setToast] = useState<{show: boolean, message: string}>({ show: false, message: '' });

  const [isEditing, setIsEditing] = useState(false);
  const [editedTitle, setEditedTitle] = useState(template.title);
  const [editedDescription, setEditedDescription] = useState(template.description);
  const [editedTags, setEditedTags] = useState(template.tags.join(', '));
  const [isGeneratingNewImage, setIsGeneratingNewImage] = useState(false);
  const [newImagePrompt, setNewImagePrompt] = useState('');
  const [newImageAspectRatio, setNewImageAspectRatio] = useState<"1:1" | "3:4" | "4:3" | "9:16" | "16:9">("4:3");
  const [newImageStyle, setNewImageStyle] = useState('Modern, clean, and professional UI/UX (Dribbble/Behance style)');
  const [showNewImagePrompt, setShowNewImagePrompt] = useState(false);

  const handleZoomIn = (e: React.MouseEvent) => {
    e.stopPropagation();
    setZoomLevel(prev => Math.min(prev + 0.5, 4));
  };

  const handleZoomOut = (e: React.MouseEvent) => {
    e.stopPropagation();
    setZoomLevel(prev => Math.max(prev - 0.5, 0.5));
  };

  const handleResetZoom = (e: React.MouseEvent) => {
    e.stopPropagation();
    setZoomLevel(1);
    setPan({ x: 0, y: 0 });
  };

  const handleMouseDown = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (zoomLevel > 1) {
      setIsDragging(true);
      setDragStart({ x: e.clientX - pan.x, y: e.clientY - pan.y });
    }
  };

  const handleMouseMove = (e: React.MouseEvent) => {
    if (isDragging && zoomLevel > 1) {
      setPan({
        x: e.clientX - dragStart.x,
        y: e.clientY - dragStart.y
      });
    }
  };

  const handleMouseUp = () => {
    setIsDragging(false);
  };

  const handleDeleteImage = async (indexToDelete: number) => {
    if (!onUpdateTemplate) return;
    
    // Create a new array without the deleted image
    const newImages = images.filter((_, idx) => idx !== indexToDelete);
    
    // If we deleted the last image, maybe we shouldn't allow it, or we fallback to the default.
    // Let's allow it, but if it's empty, the fallback will kick in on next render.
    const updatedTemplate = {
      ...template,
      images: newImages
    };
    
    // Adjust active index if necessary
    if (activeImageIndex >= newImages.length) {
      setActiveImageIndex(Math.max(0, newImages.length - 1));
    }
    
    onUpdateTemplate(updatedTemplate);
    setToast({ show: true, message: 'Imagem excluída com sucesso!' });
    setTimeout(() => setToast({ show: false, message: '' }), 3000);
  };

  const handleGenerateNewImage = async () => {
    if (!onUpdateTemplate || !newImagePrompt.trim()) return;
    
    setIsGeneratingNewImage(true);
    try {
      const newImageUrl = await generateTemplateImage(
        template.title, 
        newImagePrompt, 
        undefined, 
        'image/jpeg', 
        newImageAspectRatio, 
        newImageStyle
      );
      
      const newImage: TemplateImage = {
        url: newImageUrl,
        caption: newImagePrompt,
        type: 'mockup'
      };
      
      // If the current images are just the fallback, replace them, otherwise append
      const currentImages = hasImages ? template.images : [];
      const updatedImages = [...currentImages, newImage];
      
      const updatedTemplate = {
        ...template,
        images: updatedImages
      };
      
      onUpdateTemplate(updatedTemplate);
      setActiveImageIndex(updatedImages.length - 1);
      setShowNewImagePrompt(false);
      setNewImagePrompt('');
      setToast({ show: true, message: 'Nova imagem gerada com sucesso!' });
    } catch (error) {
      console.error('Error generating image:', error);
      setToast({ show: true, message: 'Erro ao gerar imagem. Tente novamente.' });
    } finally {
      setIsGeneratingNewImage(false);
      setTimeout(() => setToast({ show: false, message: '' }), 3000);
    }
  };

  // Load user collections on mount
  useEffect(() => {
    const saved = localStorage.getItem('dg_user_collections');
    if (saved) {
      setUserCollections(JSON.parse(saved));
    } else {
      setUserCollections({ 'My Favorites': [], 'In Progress': [], 'Inspiration': [] });
    }
  }, []);

  // Related Templates Logic
  const relatedTemplates = React.useMemo(() => {
    return allTemplates
      .filter(t => t.id !== template.id)
      .map(t => {
        let score = 0;
        if (t.category === template.category) score += 3;
        const matchingTags = t.tags.filter(tag => template.tags.includes(tag));
        score += matchingTags.length;
        return { ...t, score };
      })
      .filter(t => t.score > 0)
      .sort((a, b) => b.score - a.score)
      .slice(0, 4);
  }, [allTemplates, template]);

  // Reset state when template changes
  useEffect(() => {
    setActiveImageIndex(0);
    setActiveTab('overview');
    setIsDescriptionExpanded(false);
  }, [template.id]);

  useEffect(() => {
    setZoomLevel(1);
    setPan({ x: 0, y: 0 });
  }, [isZoomModalOpen, activeImageIndex]);

  const handleUseTemplate = async () => {
    setShowUseConfirmation(false);
    setIsDownloading(true);
    setToast({ show: true, message: 'Preparing template package & PRD...' });

    try {
      const zip = new JSZip();
      const folderName = template.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
      const mainFolder = zip.folder(folderName);

      const prdContent = generatePRD(template, images);
      mainFolder.file("PRD_Documentation.md", prdContent);
      mainFolder.file("template_data.json", JSON.stringify(template, null, 2));

      const assetsFolder = mainFolder.folder("assets");
      const imagePromises = images.map(async (img, idx) => {
        try {
          const response = await fetch(img.url);
          const blob = await response.blob();
          const contentType = response.headers.get('content-type');
          let ext = 'png';
          if (contentType?.includes('jpeg')) ext = 'jpg';
          else if (contentType?.includes('webp')) ext = 'webp';
          
          const filename = `${idx + 1}_${img.caption.replace(/\s+/g, '_')}.${ext}`;
          assetsFolder.file(filename, blob);
        } catch (err) {
          console.warn(`Failed to fetch image: ${img.url}`, err);
        }
      });

      await Promise.all(imagePromises);
      const content = await zip.generateAsync({ type: "blob" });
      const url = window.URL.createObjectURL(content);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${folderName}_package.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      if (onDownload) onDownload(template.id);
      setToast({ show: true, message: 'Package downloaded successfully!' });
    } catch (error) {
      console.error("Download failed", error);
      setToast({ show: true, message: 'Failed to generate package.' });
    } finally {
      setIsDownloading(false);
      setTimeout(() => setToast({ show: false, message: '' }), 4000);
    }
  };

  const handleShare = async () => {
    const shareUrl = `${window.location.origin}/#template/${template.id}`;
    if (navigator.share) {
      try {
        await navigator.share({ title: template.title, url: shareUrl });
        return;
      } catch (err) { }
    }
    try {
      await navigator.clipboard.writeText(shareUrl);
      setIsCopied(true);
      setShowShareMenu(true);
      setTimeout(() => { setIsCopied(false); setShowShareMenu(false); }, 2000);
    } catch (err) { }
  };

  const toggleCollection = (collectionName: string) => {
    const currentIds = userCollections[collectionName] || [];
    const exists = currentIds.includes(template.id);
    let newIds = exists ? currentIds.filter(id => id !== template.id) : [...currentIds, template.id];
    const updatedCollections = { ...userCollections, [collectionName]: newIds };
    setUserCollections(updatedCollections);
    // Use safe storage wrapper
    saveToStorage('dg_user_collections', updatedCollections);
    if (!exists) setToast({ show: true, message: `Saved to ${collectionName}` });
    setTimeout(() => setToast({ show: false, message: '' }), 3000);
  };

  const createCollection = () => {
    if (!newCollectionName.trim() || userCollections[newCollectionName]) return;
    const updated = { ...userCollections, [newCollectionName]: [template.id] };
    setUserCollections(updated);
    // Use safe storage wrapper
    saveToStorage('dg_user_collections', updated);
    setNewCollectionName('');
    setToast({ show: true, message: `Created and saved to ${newCollectionName}` });
    setTimeout(() => setToast({ show: false, message: '' }), 3000);
  };
  
  const handleSubmitReview = () => {
    if (!newComment.trim()) return;
    const comment: Comment = {
      id: Math.random().toString(36),
      user: { name: 'You', avatar: 'https://ui-avatars.com/api/?name=You&background=6366f1&color=fff' },
      rating: newRating,
      date: 'Just now',
      content: newComment
    };
    setComments([comment, ...comments]);
    setNewComment('');
    setNewRating(5);
    setToast({ show: true, message: 'Review posted successfully' });
    setTimeout(() => setToast({ show: false, message: '' }), 3000);
  };

  const formatNumber = (num: number) => num >= 1000 ? (num / 1000).toFixed(1) + 'k' : num;

  return (
    <div className="space-y-6 animate-fade-in-up relative pb-24 md:pb-10 min-h-screen">
      {/* Toast Notification */}
      {toast.show && (
        <div className="fixed top-20 right-4 left-4 md:left-auto md:right-6 z-[100] animate-fade-in-up">
          <div className="bg-slate-900 text-white px-4 py-3 rounded-lg shadow-xl flex items-center gap-3">
             <Check className="w-5 h-5 text-green-400" />
             <p className="font-medium text-sm">{toast.message}</p>
          </div>
        </div>
      )}

      {/* Nav */}
      <button onClick={onBack} className="flex items-center gap-2 text-slate-500 hover:text-indigo-600 font-medium">
        <ArrowLeft className="w-4 h-4" /> <span className="hidden sm:inline">Back to Dashboard</span> <span className="sm:hidden">Back</span>
      </button>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Gallery & Content */}
        <div className="lg:col-span-2 space-y-6">
          <div className="space-y-4">
            <div className="flex justify-between items-center">
              <h2 className="text-xl font-bold text-slate-900 hidden md:block">Galeria</h2>
              {onUpdateTemplate && (
                <button 
                  onClick={() => setIsEditing(!isEditing)}
                  className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ml-auto ${isEditing ? 'bg-indigo-100 text-indigo-700' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}
                >
                  <PenTool className="w-4 h-4" />
                  {isEditing ? 'Concluir Edição' : 'Editar Template'}
                </button>
              )}
            </div>
            <div className="bg-white rounded-2xl overflow-hidden shadow-lg border border-slate-100 relative group aspect-video bg-slate-50 select-none">
              <img 
                src={images[activeImageIndex]?.url || ''} 
                alt={images[activeImageIndex]?.caption || ''} 
                className="w-full h-full object-cover object-top cursor-zoom-in transition-transform duration-700 hover:scale-105"
                onClick={() => setIsZoomModalOpen(true)}
              />
              <div className="absolute top-4 left-4 bg-black/70 text-white px-3 py-1 rounded-full text-[10px] md:text-xs font-medium backdrop-blur-md z-10">
                 {images[activeImageIndex]?.caption}
              </div>
              <button onClick={() => setIsZoomModalOpen(true)} className="absolute top-4 right-4 p-2 bg-white/20 hover:bg-white rounded-full backdrop-blur-md text-white hover:text-indigo-600 z-20 transition-all">
                <Maximize2 className="w-5 h-5" />
              </button>
              {images.length > 1 && (
                <>
                  <button onClick={() => setActiveImageIndex(c => (c === 0 ? images.length - 1 : c - 1))} className="absolute left-2 md:left-4 top-1/2 -translate-y-1/2 p-2 bg-white/90 rounded-full text-slate-800 shadow-lg backdrop-blur-sm z-10 transition-all hover:scale-110"><ChevronLeft className="w-5 h-5 md:w-6 md:h-6" /></button>
                  <button onClick={() => setActiveImageIndex(c => (c + 1) % images.length)} className="absolute right-2 md:right-4 top-1/2 -translate-y-1/2 p-2 bg-white/90 rounded-full text-slate-800 shadow-lg backdrop-blur-sm z-10 transition-all hover:scale-110"><ChevronRight className="w-5 h-5 md:w-6 md:h-6" /></button>
                </>
              )}
            </div>
            {(images.length > 1 || isEditing) && (
              <div className="flex gap-2 overflow-x-auto pb-2 scrollbar-hide px-1">
                {images.map((img, idx) => (
                  <div key={idx} className="relative flex-shrink-0 w-16 h-16 md:w-20 md:h-20">
                    <button onClick={() => setActiveImageIndex(idx)} className={`w-full h-full rounded-lg overflow-hidden border-2 transition-all ${activeImageIndex === idx ? 'border-indigo-600 ring-2 ring-indigo-600/20' : 'border-transparent opacity-60'}`}>
                      <img src={img.url} className="w-full h-full object-cover" />
                    </button>
                    {isEditing && (
                      <button 
                        onClick={() => handleDeleteImage(idx)}
                        className="absolute -top-2 -right-2 p-1 bg-red-500 text-white rounded-full hover:bg-red-600 shadow-sm z-10"
                        title="Excluir imagem"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    )}
                  </div>
                ))}
                {isEditing && (
                  <button 
                    onClick={() => setShowNewImagePrompt(true)}
                    className="flex-shrink-0 w-16 h-16 md:w-20 md:h-20 rounded-lg border-2 border-dashed border-slate-300 flex items-center justify-center text-slate-400 hover:text-indigo-600 hover:border-indigo-400 hover:bg-indigo-50 transition-colors"
                  >
                    <Plus className="w-6 h-6" />
                  </button>
                )}
              </div>
            )}
          </div>

          {/* Tabs */}
          <div className="border-b border-slate-200 sticky top-[89px] bg-slate-50 z-20 -mx-4 px-4">
             <div className="flex gap-4 md:gap-6 overflow-x-auto pb-px no-scrollbar">
                {['overview', 'features', 'reviews', 'related'].map((tab) => (
                   <button key={tab} onClick={() => setActiveTab(tab as any)} className={`pb-3 text-sm font-medium capitalize transition-colors relative whitespace-nowrap px-1 ${activeTab === tab ? 'text-indigo-600' : 'text-slate-500 hover:text-slate-700'}`}>{tab}{activeTab === tab && <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-indigo-600 rounded-t-full" />}</button>
                ))}
             </div>
          </div>

          <div className="bg-white rounded-2xl p-4 md:p-6 border border-slate-100 shadow-sm min-h-[300px]">
             {activeTab === 'overview' && (
                <div className="space-y-6">
                   <div>
                     <div className="flex justify-between items-center mb-3">
                       <h3 className="text-lg font-bold text-slate-900">Sobre este template</h3>
                       {onUpdateTemplate && (
                         <button 
                           onClick={() => {
                             if (isEditing) {
                               onUpdateTemplate({
                                 ...template,
                                 title: editedTitle,
                                 description: editedDescription,
                                 tags: editedTags.split(',').map(t => t.trim()).filter(Boolean)
                               });
                               setToast({ show: true, message: 'Informações atualizadas!' });
                               setTimeout(() => setToast({ show: false, message: '' }), 3000);
                             }
                             setIsEditing(!isEditing);
                           }}
                           className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${isEditing ? 'bg-indigo-100 text-indigo-700' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}
                         >
                           <PenTool className="w-4 h-4" />
                           {isEditing ? 'Salvar Informações' : 'Editar Informações'}
                         </button>
                       )}
                     </div>
                     
                     {isEditing ? (
                       <div className="space-y-4 animate-fade-in">
                         <div>
                           <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Título</label>
                           <input 
                             type="text" 
                             value={editedTitle} 
                             onChange={e => setEditedTitle(e.target.value)}
                             className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500/20 outline-none font-bold text-slate-900"
                           />
                         </div>
                         <div>
                           <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Descrição</label>
                           <textarea 
                             value={editedDescription} 
                             onChange={e => setEditedDescription(e.target.value)}
                             className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500/20 outline-none min-h-[120px] resize-y text-slate-600"
                           />
                         </div>
                         <div>
                           <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Tags (separadas por vírgula)</label>
                           <input 
                             type="text" 
                             value={editedTags} 
                             onChange={e => setEditedTags(e.target.value)}
                             className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500/20 outline-none text-slate-600"
                           />
                         </div>
                       </div>
                     ) : (
                       <div className="relative">
                         <p className={`text-slate-600 leading-relaxed text-sm md:text-base transition-all ${isDescriptionExpanded ? '' : 'line-clamp-4'}`}>{template.description}</p>
                         {template.description.length > 250 && (
                            <button onClick={() => setIsDescriptionExpanded(!isDescriptionExpanded)} className="mt-2 text-indigo-600 font-medium text-sm flex items-center gap-1">{isDescriptionExpanded ? <>Show Less <ChevronUp className="w-4 h-4" /></> : <>Read More <ChevronDown className="w-4 h-4" /></>}</button>
                         )}
                       </div>
                     )}
                   </div>
                   <div className="grid grid-cols-2 gap-3 md:gap-4 pt-4">
                      <div className="bg-slate-50 p-3 md:p-4 rounded-xl">
                         <div className="text-[10px] md:text-sm text-slate-500 mb-0.5 md:mb-1 uppercase tracking-wider font-bold">Created</div>
                         <div className="font-semibold text-xs md:text-sm">{new Date(template.createdAt).toLocaleDateString()}</div>
                      </div>
                      <div className="bg-slate-50 p-3 md:p-4 rounded-xl">
                         <div className="text-[10px] md:text-sm text-slate-500 mb-0.5 md:mb-1 uppercase tracking-wider font-bold">Version</div>
                         <div className="font-semibold text-xs md:text-sm">{template.version}</div>
                      </div>
                      <div className="bg-slate-50 p-3 md:p-4 rounded-xl">
                         <div className="text-[10px] md:text-sm text-slate-500 mb-0.5 md:mb-1 uppercase tracking-wider font-bold">License</div>
                         <div className="font-semibold text-xs md:text-sm capitalize">{template.pricing}</div>
                      </div>
                   </div>
                </div>
             )}

             {activeTab === 'features' && (
               <div className="space-y-4">
                 <div className="flex justify-between items-center">
                   <h3 className="text-lg font-bold text-slate-900">Key Features</h3>
                   {onUpdateTemplate && (
                     <button 
                       onClick={() => {
                         if (isEditing) {
                           onUpdateTemplate({
                             ...template,
                             title: editedTitle,
                             description: editedDescription,
                             tags: editedTags.split(',').map(t => t.trim()).filter(Boolean)
                           });
                           setToast({ show: true, message: 'Informações atualizadas!' });
                           setTimeout(() => setToast({ show: false, message: '' }), 3000);
                         }
                         setIsEditing(!isEditing);
                       }}
                       className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${isEditing ? 'bg-indigo-100 text-indigo-700' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}
                     >
                       <PenTool className="w-4 h-4" />
                       {isEditing ? 'Salvar' : 'Editar'}
                     </button>
                   )}
                 </div>
                 {isEditing ? (
                   <div className="space-y-3">
                     <p className="text-xs text-slate-500 mb-2">Edite as funcionalidades abaixo. (Apenas visualização no modo de edição simplificado)</p>
                     <ul className="grid grid-cols-1 md:grid-cols-2 gap-3">
                        {template.features.map((feature, idx) => (
                           <li key={idx} className="flex items-start gap-2 text-slate-600 p-3 bg-white border border-slate-200 rounded-lg text-sm md:text-base">
                              <Check className="w-5 h-5 text-slate-300 shrink-0 mt-0.5" />
                              <input 
                                type="text" 
                                defaultValue={feature}
                                className="w-full bg-transparent outline-none"
                                readOnly
                              />
                           </li>
                        ))}
                     </ul>
                   </div>
                 ) : (
                   <ul className="grid grid-cols-1 md:grid-cols-2 gap-3">
                      {template.features.map((feature, idx) => (
                         <li key={idx} className="flex items-start gap-2 text-slate-600 p-3 bg-slate-50 rounded-lg text-sm md:text-base">
                            <Check className="w-5 h-5 text-green-500 shrink-0 mt-0.5" />
                            <span>{feature}</span>
                         </li>
                      ))}
                   </ul>
                 )}
               </div>
             )}
             
             {activeTab === 'reviews' && (
               <div className="space-y-6">
                  <div className="flex flex-col sm:flex-row items-center gap-6 p-4 md:p-6 bg-slate-50 rounded-xl border border-slate-100">
                     <div className="text-center">
                        <div className="text-4xl md:text-5xl font-bold text-slate-900">4.8</div>
                        <div className="flex text-yellow-400 justify-center my-2 gap-0.5"><Star className="w-4 h-4 fill-current" /><Star className="w-4 h-4 fill-current" /><Star className="w-4 h-4 fill-current" /><Star className="w-4 h-4 fill-current" /><Star className="w-4 h-4 fill-current" /></div>
                        <div className="text-xs text-slate-500">{comments.length} reviews</div>
                     </div>
                     <div className="flex-1 w-full sm:border-l border-slate-200 sm:pl-8 space-y-2">
                        {[5,4,3,2,1].map(rating => (
                           <div key={rating} className="flex items-center gap-2">
                              <span className="text-xs font-medium w-3">{rating}</span>
                              <div className="flex-1 h-1.5 bg-slate-200 rounded-full overflow-hidden"><div className="h-full bg-yellow-400 rounded-full" style={{ width: rating === 5 ? '70%' : rating === 4 ? '20%' : '5%' }}></div></div>
                           </div>
                        ))}
                     </div>
                  </div>
                  
                  {/* Rating Form */}
                  <div className="bg-white p-4 md:p-6 rounded-xl border border-slate-100 shadow-sm">
                     <h4 className="font-bold text-slate-900 mb-4">Leave a Review</h4>
                     <div className="flex items-center gap-2 mb-4">
                        {[1, 2, 3, 4, 5].map(star => (
                           <button 
                              key={star} 
                              onClick={() => setNewRating(star)}
                              className={`p-1 transition-colors ${star <= newRating ? 'text-yellow-400' : 'text-slate-200 hover:text-yellow-200'}`}
                           >
                              <Star className="w-6 h-6 fill-current" />
                           </button>
                        ))}
                     </div>
                     <textarea 
                        value={newComment}
                        onChange={(e) => setNewComment(e.target.value)}
                        placeholder="What do you think about this template?"
                        className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-indigo-500/20 outline-none resize-none min-h-[100px] mb-3"
                     />
                     <div className="flex justify-end">
                        <button 
                           onClick={handleSubmitReview}
                           disabled={!newComment.trim()}
                           className="px-6 py-2.5 bg-indigo-600 text-white rounded-xl text-sm font-bold hover:bg-indigo-700 disabled:opacity-50 flex items-center gap-2"
                        >
                           <Send className="w-4 h-4" /> Post Review
                        </button>
                     </div>
                  </div>

                  <div className="space-y-4">
                     {comments.map(comment => (
                        <div key={comment.id} className="flex gap-3 md:gap-4 p-3 md:p-4 rounded-xl bg-slate-50 border border-slate-100">
                           <img src={comment.user.avatar} className="w-8 h-8 md:w-10 md:h-10 rounded-full flex-shrink-0" />
                           <div className="flex-1 min-w-0">
                              <div className="flex items-center justify-between mb-1">
                                 <h4 className="font-semibold text-slate-900 text-sm truncate">{comment.user.name}</h4>
                                 <span className="text-[10px] text-slate-400">{comment.date}</span>
                              </div>
                              <div className="flex text-yellow-400 mb-2 gap-0.5">
                                 {[...Array(5)].map((_, i) => (
                                    <Star key={i} className={`w-3 h-3 ${i < comment.rating ? 'fill-current' : 'text-slate-200'}`} />
                                 ))}
                              </div>
                              <p className="text-slate-600 text-xs md:text-sm leading-relaxed">{comment.content}</p>
                           </div>
                        </div>
                     ))}
                  </div>
               </div>
             )}

             {activeTab === 'related' && (
               <div className="grid grid-cols-2 md:grid-cols-2 gap-4">
                 {relatedTemplates.map(related => (
                    <div key={related.id} onClick={() => onNavigateToDetails?.(related)} className="border border-slate-200 rounded-xl overflow-hidden hover:shadow-md cursor-pointer group">
                       <img src={related.images[0].url} className="w-full h-24 md:h-32 object-cover transition-transform group-hover:scale-105" />
                       <div className="p-2 md:p-3">
                          <div className="font-semibold text-xs md:text-sm mb-1 truncate">{related.title}</div>
                          <div className="text-[10px] text-slate-500 uppercase font-bold">{related.category}</div>
                       </div>
                    </div>
                 ))}
               </div>
             )}
          </div>
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
           <div className="bg-white rounded-2xl p-4 md:p-6 border border-slate-100 shadow-sm space-y-6">
              <div className="space-y-4">
                <div className="inline-block px-3 py-1 rounded-full bg-indigo-50 text-indigo-700 text-[10px] font-bold uppercase tracking-widest">Mobile UI Kit</div>
                <h1 className="text-xl md:text-2xl font-bold text-slate-900 leading-tight">{template.title}</h1>
                <p className="text-sm text-slate-500 leading-relaxed">{template.description}</p>
                <div className="flex items-center gap-2">
                  <div className="flex text-yellow-400 gap-0.5"><Star className="w-4 h-4 fill-current" /><Star className="w-4 h-4 fill-current" /><Star className="w-4 h-4 fill-current" /><Star className="w-4 h-4 fill-current" /><Star className="w-4 h-4 fill-current" /></div>
                  <span className="text-xs text-slate-500 font-medium">({template.stats.likes} reviews)</span>
                </div>
                <div className="flex flex-wrap items-center gap-4 text-xs font-bold text-slate-400 pt-2">
                   <div className="flex items-center gap-1 uppercase tracking-wider"><Eye className="w-3.5 h-3.5" /> {formatNumber(template.stats.views)}</div>
                   <div className="flex items-center gap-1 uppercase tracking-wider"><Download className="w-3.5 h-3.5" /> {formatNumber(template.stats.downloads)}</div>
                   <button onClick={() => onLike(template.id)} className={`flex items-center gap-1 uppercase tracking-wider transition-colors ${isLiked ? 'text-pink-500' : 'hover:text-pink-500'}`}>
                      <Heart className={`w-3.5 h-3.5 ${isLiked ? 'fill-current' : ''}`} /> {formatNumber(template.stats.likes)}
                   </button>
                </div>
              </div>

              {/* Design Elements Section */}
              {template.designElements && template.designElements.length > 0 && (
                <div className="bg-indigo-50/50 rounded-2xl p-4 border border-indigo-100">
                   <h4 className="text-xs font-bold text-indigo-900 mb-3 flex items-center gap-2 uppercase tracking-widest"><Palette className="w-4 h-4 text-indigo-500" /> Diretrizes Visuais</h4>
                   <ul className="space-y-2">
                     {template.designElements.map((el, idx) => (
                        <li key={idx} className="flex items-start gap-2 text-xs text-indigo-800">
                           <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 mt-1.5 flex-shrink-0" />
                           <span className="leading-snug">{el}</span>
                        </li>
                     ))}
                   </ul>
                </div>
              )}

              {/* Features Section */}
              <div className="bg-slate-50 rounded-2xl p-4 border border-slate-100">
                 <h4 className="text-xs font-bold text-slate-800 mb-4 flex items-center gap-2 uppercase tracking-widest"><Layers className="w-4 h-4 text-slate-500" /> Funcionalidades</h4>
                 <ul className="space-y-2.5">
                     {template.features?.map((feature, idx) => {
                         const hasImg = template.images && template.images.some(img => img.caption === feature);
                         return (
                           <li key={idx} className="flex items-center gap-3 text-xs md:text-sm text-slate-600">
                               <div className={`w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 ${hasImg ? 'bg-green-100' : 'bg-slate-200'}`}>{hasImg ? <Check className="w-3 h-3 text-green-600" /> : <div className="w-1.5 h-1.5 rounded-full bg-slate-400" />}</div>
                               <span className={hasImg ? 'text-slate-900 font-bold' : 'text-slate-500'}>{feature}</span>
                           </li>
                         );
                     })}
                 </ul>
              </div>

              <div className="pt-4 border-t border-slate-100 flex items-center justify-between text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                 <span className="flex items-center gap-1"><MonitorSmartphone className="w-3 h-3" /> Responsive</span>
                 <span className="flex items-center gap-1"><Palette className="w-3 h-3" /> Design System</span>
              </div>

              {/* Desktop CTA */}
              <div className="hidden md:block space-y-3 pt-4 border-t border-slate-100">
                 <button onClick={() => setShowUseConfirmation(true)} disabled={isDownloading} className="w-full bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-4 rounded-xl font-bold shadow-lg shadow-indigo-500/20 transition-all flex items-center justify-center gap-2 text-lg">
                    {isDownloading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Download className="w-5 h-5" />}
                    {template.pricing === 'free' ? 'Use Template' : `Purchase $${template.price}`}
                 </button>
                 <div className="flex gap-2">
                   <button onClick={() => setShowCollectionModal(true)} className="flex-1 py-3 rounded-xl border border-slate-200 text-slate-600 hover:bg-slate-50 font-bold text-sm flex items-center justify-center gap-2"><BookmarkPlus className="w-4 h-4" /> Save</button>
                   <button onClick={handleShare} className="flex-1 py-3 rounded-xl border border-slate-200 text-slate-600 hover:bg-slate-50 font-bold text-sm flex items-center justify-center gap-2"><Share2 className="w-4 h-4" /> Share</button>
                 </div>
              </div>

              <div className="pt-4 border-t border-slate-100 flex items-center gap-3">
                 <img src={template.author.avatar} className="w-10 h-10 rounded-full border border-slate-100" />
                 <div className="min-w-0">
                    <div className="font-bold text-sm text-slate-900 truncate">{template.author.name} {template.author.verified && <span className="text-blue-500 ml-1">✓</span>}</div>
                    <div className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Author</div>
                 </div>
              </div>
           </div>

           <div className="bg-white rounded-2xl p-4 md:p-6 border border-slate-100 shadow-sm">
              <h4 className="font-bold text-slate-900 mb-4 text-xs uppercase tracking-widest">Available Tags</h4>
              <div className="flex flex-wrap gap-2">
                 {template.tags.map(tag => (
                    <span key={tag} className="px-3 py-1.5 bg-slate-50 text-slate-600 rounded-lg text-[10px] md:text-xs font-medium hover:bg-slate-100 cursor-pointer">#{tag}</span>
                 ))}
              </div>
           </div>
        </div>
      </div>

      {/* Sticky Bottom Bar for Mobile */}
      <div className="md:hidden fixed bottom-0 left-0 right-0 p-4 bg-white/80 backdrop-blur-lg border-t border-slate-200 z-[40] flex gap-3 shadow-[0_-4px_20px_rgba(0,0,0,0.05)]">
        <button onClick={() => setShowCollectionModal(true)} className="p-3.5 bg-slate-100 text-slate-600 rounded-xl hover:bg-slate-200"><BookmarkPlus className="w-6 h-6" /></button>
        <button onClick={() => setShowUseConfirmation(true)} disabled={isDownloading} className="flex-1 bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3.5 rounded-xl shadow-lg flex items-center justify-center gap-2">
           {isDownloading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Download className="w-5 h-5" />}
           {template.pricing === 'free' ? 'Use Template' : `$${template.price}`}
        </button>
      </div>

      {/* Confirmation Modal */}
      {showUseConfirmation && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-fade-in" onClick={() => setShowUseConfirmation(false)}>
          <div className="bg-white rounded-2xl max-w-md w-full p-6 shadow-2xl animate-fade-in-up" onClick={e => e.stopPropagation()}>
            <div className="w-12 h-12 rounded-full bg-indigo-50 flex items-center justify-center mx-auto mb-4">
              <Download className="w-6 h-6 text-indigo-600" />
            </div>
            <h3 className="text-xl font-bold text-center text-slate-900 mb-2">Use Template</h3>
            <p className="text-slate-500 text-center mb-6 text-sm">Are you sure you want to download <b>{template.title}</b>? Includes assets, JSON data, and PRD.</p>
            <div className="flex gap-3">
              <button onClick={() => setShowUseConfirmation(false)} className="flex-1 py-3 bg-slate-100 text-slate-700 font-bold rounded-xl hover:bg-slate-200 transition-all">Cancel</button>
              <button onClick={handleUseTemplate} className="flex-1 py-3 bg-indigo-600 text-white font-bold rounded-xl hover:bg-indigo-700 shadow-md transition-all">Confirm</button>
            </div>
          </div>
        </div>
      )}

      {/* Collection Modal */}
      {showCollectionModal && (
        <div className="fixed inset-0 z-[110] flex items-end md:items-center justify-center md:p-4 bg-black/50 backdrop-blur-sm animate-fade-in" onClick={() => setShowCollectionModal(false)}>
          <div className="bg-white rounded-t-3xl md:rounded-3xl max-w-sm w-full shadow-2xl overflow-hidden animate-fade-in-up" onClick={e => e.stopPropagation()}>
            <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-slate-50">
               <h3 className="font-bold text-slate-800">Save to Collection</h3>
               <button onClick={() => setShowCollectionModal(false)} className="p-2 text-slate-400 hover:text-slate-600"><X className="w-5 h-5" /></button>
            </div>
            <div className="p-2 max-h-[50vh] overflow-y-auto">
               <div className="space-y-1">
                 {Object.entries(userCollections).map(([colName, items]) => {
                   const collectionItems = items as string[];
                   const isSaved = collectionItems.includes(template.id);
                   return (
                    <button key={colName} onClick={() => toggleCollection(colName)} className={`w-full text-left px-4 py-3 rounded-xl transition-all flex items-center justify-between group ${isSaved ? 'bg-indigo-50 text-indigo-700' : 'hover:bg-slate-50 text-slate-700'}`}>
                      <div className="flex items-center gap-3">
                        <FolderPlus className={`w-5 h-5 ${isSaved ? 'text-indigo-600' : 'text-slate-400'}`} />
                        <span className="font-bold text-sm">{colName} <span className="font-normal opacity-50 ml-1">({collectionItems.length})</span></span>
                      </div>
                      {isSaved && <Check className="w-4 h-4 text-indigo-600" />}
                    </button>
                   );
                 })}
               </div>
            </div>
            <div className="p-4 border-t border-slate-100 bg-white">
              <div className="flex gap-2">
                <input type="text" value={newCollectionName} onChange={(e) => setNewCollectionName(e.target.value)} placeholder="New collection..." className="flex-1 px-3 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-indigo-500/20 outline-none" />
                <button onClick={createCollection} disabled={!newCollectionName.trim()} className="px-4 py-2.5 bg-indigo-600 text-white rounded-xl text-sm font-bold hover:bg-indigo-700 disabled:opacity-50">Add</button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* New Image Prompt Modal */}
      {showNewImagePrompt && (
        <div className="fixed inset-0 z-[110] flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-fade-in" onClick={() => !isGeneratingNewImage && setShowNewImagePrompt(false)}>
          <div className="bg-white rounded-2xl max-w-md w-full p-6 shadow-2xl animate-fade-in-up" onClick={e => e.stopPropagation()}>
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-xl font-bold text-slate-900">Gerar Nova Imagem</h3>
              <button onClick={() => !isGeneratingNewImage && setShowNewImagePrompt(false)} className="text-slate-400 hover:text-slate-600">
                <X className="w-5 h-5" />
              </button>
            </div>
            <p className="text-slate-500 text-sm mb-4">
              Descreva o que você gostaria de ver na nova imagem para este template. A IA irá gerar uma imagem baseada na sua descrição e no título do template.
            </p>
            <div className="mb-4">
              <label className="block text-sm font-medium text-slate-700 mb-2">Descrição da Imagem</label>
              <textarea
                value={newImagePrompt}
                onChange={(e) => setNewImagePrompt(e.target.value)}
                placeholder="Ex: Tela de login com tema escuro e botões arredondados..."
                className="w-full px-4 py-3 rounded-xl border border-slate-200 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 outline-none resize-none h-24 text-sm"
                disabled={isGeneratingNewImage}
              />
            </div>
            <div className="grid grid-cols-2 gap-4 mb-6">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">Proporção</label>
                <div className="relative">
                  <select
                    value={newImageAspectRatio}
                    onChange={(e) => setNewImageAspectRatio(e.target.value as any)}
                    className="w-full appearance-none px-4 py-2.5 rounded-xl border border-slate-200 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 outline-none text-sm bg-white"
                    disabled={isGeneratingNewImage}
                  >
                    <option value="1:1">1:1 (Quadrado)</option>
                    <option value="4:3">4:3 (Padrão)</option>
                    <option value="16:9">16:9 (Widescreen)</option>
                    <option value="3:4">3:4 (Retrato)</option>
                    <option value="9:16">9:16 (Mobile)</option>
                  </select>
                  <ChevronDown className="w-4 h-4 text-slate-400 absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">Estilo</label>
                <div className="relative">
                  <select
                    value={newImageStyle}
                    onChange={(e) => setNewImageStyle(e.target.value)}
                    className="w-full appearance-none px-4 py-2.5 rounded-xl border border-slate-200 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 outline-none text-sm bg-white"
                    disabled={isGeneratingNewImage}
                  >
                    <option value="Modern, clean, and professional UI/UX (Dribbble/Behance style)">Moderno / Clean</option>
                    <option value="3D render, highly detailed, soft lighting, claymorphism">Render 3D</option>
                    <option value="Minimalist, lots of whitespace, typography focused, monochrome">Minimalista</option>
                    <option value="Flat design, vibrant colors, vector illustrations">Flat Design</option>
                    <option value="Isometric view, 3D mockup, floating elements">Isométrico</option>
                  </select>
                  <ChevronDown className="w-4 h-4 text-slate-400 absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" />
                </div>
              </div>
            </div>
            <div className="flex gap-3">
              <button 
                onClick={() => setShowNewImagePrompt(false)} 
                className="flex-1 py-3 bg-slate-100 text-slate-700 font-bold rounded-xl hover:bg-slate-200 transition-all"
                disabled={isGeneratingNewImage}
              >
                Cancelar
              </button>
              <button 
                onClick={handleGenerateNewImage} 
                className="flex-1 py-3 bg-indigo-600 text-white font-bold rounded-xl hover:bg-indigo-700 shadow-md transition-all flex items-center justify-center gap-2"
                disabled={isGeneratingNewImage || !newImagePrompt.trim()}
              >
                {isGeneratingNewImage ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Gerando...
                  </>
                ) : (
                  'Gerar Imagem'
                )}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Interactive Zoom Modal */}
      {isZoomModalOpen && (
         <div 
            className="fixed inset-0 z-[120] bg-black/95 flex flex-col animate-fade-in" 
            onClick={() => setIsZoomModalOpen(false)}
            onMouseMove={handleMouseMove}
            onMouseUp={handleMouseUp}
            onMouseLeave={handleMouseUp}
         >
            <div className="p-4 flex justify-between items-center z-10">
               <div className="flex gap-2" onClick={e => e.stopPropagation()}>
                  <button onClick={handleZoomOut} className="p-2 bg-white/10 text-white rounded-lg hover:bg-white/20"><ZoomOut className="w-5 h-5" /></button>
                  <button onClick={handleResetZoom} className="p-2 bg-white/10 text-white rounded-lg hover:bg-white/20"><RotateCcw className="w-5 h-5" /></button>
                  <button onClick={handleZoomIn} className="p-2 bg-white/10 text-white rounded-lg hover:bg-white/20"><ZoomIn className="w-5 h-5" /></button>
                  <span className="text-white/60 text-sm font-medium flex items-center px-2">{Math.round(zoomLevel * 100)}%</span>
               </div>
               <button onClick={() => setIsZoomModalOpen(false)} className="p-3 bg-white/10 text-white rounded-full hover:bg-white/20"><X className="w-6 h-6" /></button>
            </div>
            <div className="flex-1 flex items-center justify-center overflow-hidden relative">
               <div 
                  className={`transition-transform ${isDragging ? 'duration-0 cursor-grabbing' : 'duration-200 cursor-grab'}`}
                  style={{ transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoomLevel})` }}
                  onMouseDown={handleMouseDown}
                  onClick={(e) => e.stopPropagation()}
               >
                  <img src={images[activeImageIndex].url} className="max-h-[80vh] max-w-full object-contain select-none pointer-events-none" />
               </div>
            </div>
            <div className="p-8 text-center z-10"><p className="text-white/60 text-sm font-medium">{images[activeImageIndex].caption}</p></div>
         </div>
      )}
    </div>
  );
};

export default TemplateDetails;